-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 18:59:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema issue_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema issue_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `issue_manager` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `issue_manager` ;

-- -----------------------------------------------------
-- Table `issue_manager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`User` (
  `Issue_ID zadavatele` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Issue_ID zadavatele`),
  UNIQUE INDEX `Issue_ID zadavatele_UNIQUE` (`Issue_ID zadavatele` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`Issue` (
  `ID zadavatele` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `Typ` VARCHAR(2) NOT NULL,
  `stav` VARCHAR(45) NOT NULL,
  `datum zalozeni` DATETIME NOT NULL,
  `Resitel` VARCHAR(45) NOT NULL,
  `popis` VARCHAR(2000) NOT NULL,
  `start` DATETIME NOT NULL,
  `vyreseni` DATETIME NOT NULL,
  PRIMARY KEY (`ID zadavatele`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) ,
  UNIQUE INDEX `ID zadavatele_UNIQUE` (`ID zadavatele` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`Admin` (
  `IDadmin` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDadmin`),
  UNIQUE INDEX `IDadmin_UNIQUE` (`IDadmin` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`PC` (
  `Idpc` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OS` VARCHAR(45) NOT NULL,
  `jmenoprihlas` VARCHAR(45) NOT NULL,
  `prijmprihlas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Idpc`),
  UNIQUE INDEX `Id prihlaseneho_UNIQUE` (`Idpc` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`Issue_has_Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`Issue_has_Admin` (
  `Issue_ID zadavatele` INT UNSIGNED NOT NULL,
  `Admin_ID uzivatele` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Issue_ID zadavatele`, `Admin_ID uzivatele`),
  INDEX `fk_Issue_has_Admin_Admin1_idx` (`Admin_ID uzivatele` ASC) ,
  INDEX `fk_Issue_has_Admin_Issue1_idx` (`Issue_ID zadavatele` ASC) ,
  CONSTRAINT `fk_Issue_has_Admin_Issue1`
    FOREIGN KEY (`Issue_ID zadavatele`)
    REFERENCES `issue_manager`.`Issue` (`ID zadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Issue_has_Admin_Admin1`
    FOREIGN KEY (`Admin_ID uzivatele`)
    REFERENCES `issue_manager`.`Admin` (`ID uzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`User_has_PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`User_has_PC` (
  `User_Issue_ID zadavatele` INT NOT NULL,
  `PC_Idpc` INT NOT NULL,
  PRIMARY KEY (`User_Issue_ID zadavatele`, `PC_Idpc`),
  INDEX `fk_User_has_PC_PC1_idx` (`PC_Idpc` ASC) ,
  INDEX `fk_User_has_PC_User1_idx` (`User_Issue_ID zadavatele` ASC) ,
  CONSTRAINT `fk_User_has_PC_User1`
    FOREIGN KEY (`User_Issue_ID zadavatele`)
    REFERENCES `issue_manager`.`User` (`Issue_ID zadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_PC_PC1`
    FOREIGN KEY (`PC_Idpc`)
    REFERENCES `issue_manager`.`PC` (`Idpc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue_manager`.`User_has_Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue_manager`.`User_has_Issue` (
  `User_Issue_ID zadavatele` INT UNSIGNED NOT NULL,
  `Issue_ID zadavatele` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`User_Issue_ID zadavatele`, `Issue_ID zadavatele`),
  INDEX `fk_User_has_Issue_Issue1_idx` (`Issue_ID zadavatele` ASC) ,
  INDEX `fk_User_has_Issue_User1_idx` (`User_Issue_ID zadavatele` ASC) ,
  CONSTRAINT `fk_User_has_Issue_User1`
    FOREIGN KEY (`User_Issue_ID zadavatele`)
    REFERENCES `issue_manager`.`User` (`Issue_ID zadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Issue_Issue1`
    FOREIGN KEY (`Issue_ID zadavatele`)
    REFERENCES `issue_manager`.`Issue` (`ID zadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
