-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 13:31:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema issue-manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema issue-manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `issue-manager` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `issue-manager` ;

-- -----------------------------------------------------
-- Table `issue-manager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`User` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `Issue_ID zadavatele_UNIQUE` (`userID` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`Issue` (
  `IDzadavatele` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `Typ` VARCHAR(2) NOT NULL,
  `stav` VARCHAR(45) NOT NULL,
  `zalozeni` DATETIME NOT NULL,
  `Resitel` VARCHAR(45) NOT NULL,
  `popis` VARCHAR(2000) NOT NULL,
  `start` DATETIME NOT NULL,
  `vyreseni` DATETIME NOT NULL,
  PRIMARY KEY (`IDzadavatele`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) ,
  UNIQUE INDEX `ID zadavatele_UNIQUE` (`IDzadavatele` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`Admin` (
  `IDuzivatele` INT NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDuzivatele`),
  UNIQUE INDEX `ID uzivatele_UNIQUE` (`IDuzivatele` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`PC` (
  `Idpc` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OS` VARCHAR(45) NOT NULL,
  `jmenoprihlas` VARCHAR(45) NOT NULL,
  `prijmprihlas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Idpc`),
  UNIQUE INDEX `Id prihlaseneho_UNIQUE` (`Idpc` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`PC_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`PC_has_User` (
  `PC_Idpc` INT UNSIGNED NOT NULL,
  `User_userID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PC_Idpc`, `User_userID`),
  INDEX `fk_PC_has_User_User1_idx` (`User_userID` ASC) ,
  INDEX `fk_PC_has_User_PC_idx` (`PC_Idpc` ASC) ,
  CONSTRAINT `fk_PC_has_User_PC`
    FOREIGN KEY (`PC_Idpc`)
    REFERENCES `issue-manager`.`PC` (`Idpc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PC_has_User_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `issue-manager`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`User_has_Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`User_has_Issue` (
  `User_userID` INT UNSIGNED NOT NULL,
  `Issue_IDzadavatele` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`User_userID`, `Issue_IDzadavatele`),
  INDEX `fk_User_has_Issue_Issue1_idx` (`Issue_IDzadavatele` ASC) ,
  INDEX `fk_User_has_Issue_User1_idx` (`User_userID` ASC) ,
  CONSTRAINT `fk_User_has_Issue_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `issue-manager`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Issue_Issue1`
    FOREIGN KEY (`Issue_IDzadavatele`)
    REFERENCES `issue-manager`.`Issue` (`IDzadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `issue-manager`.`Issue_has_Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue-manager`.`Issue_has_Admin` (
  `Issue_IDzadavatele` INT UNSIGNED NOT NULL,
  `Admin_IDuzivatele` INT NOT NULL,
  PRIMARY KEY (`Issue_IDzadavatele`, `Admin_IDuzivatele`),
  INDEX `fk_Issue_has_Admin_Admin1_idx` (`Admin_IDuzivatele` ASC) ,
  INDEX `fk_Issue_has_Admin_Issue1_idx` (`Issue_IDzadavatele` ASC) ,
  CONSTRAINT `fk_Issue_has_Admin_Issue1`
    FOREIGN KEY (`Issue_IDzadavatele`)
    REFERENCES `issue-manager`.`Issue` (`IDzadavatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Issue_has_Admin_Admin1`
    FOREIGN KEY (`Admin_IDuzivatele`)
    REFERENCES `issue-manager`.`Admin` (`IDuzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
